QDRANT_URL="https://a889ab3c-c68f-4d2e-a478-d36e0dd9e9e0.us-east-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.QXsCCkR3BvecYXX4r5DqWcNLd1qX5W3_LgXmteTRdVw"